version: '3.3'
services:
  postgres:
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER="postgres"
      - POSTGRES_PASSWORD="admin"
      - POSTGRES_DB="insurance"
  tomcat:
    build:
      context: .
      dockerfile: /web/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - /home/tamerlan/Downloads/tomcat/conf/
      - /home/tamerlan/Downloads/tomcat/webapps
      - ./target/delete.war